# Generated by Django 3.0.5 on 2021-05-25 17:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_reviewproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewProduct',
            new_name='Review',
        ),
    ]
