# Generated by Django 3.0.5 on 2021-05-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210525_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='sno',
            new_name='product_id',
        ),
    ]
