# Generated by Django 3.0.5 on 2021-05-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210525_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='id',
        ),
    ]
